server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapping/*.xml

########################################## pagehelper分页插件配置
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  mvc:
    static-path-pattern: /**
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: oracle.jdbc.driver.OracleDriver          # oracle驱动
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: fds697097SJY
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1 from dual
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
############################################################
